using InvoiceApp.Core.Entities;
using InvoiceApp.Core.Interfaces.Services;
using iText.Html2pdf;
using iText.Kernel.Pdf;

namespace InvoiceApp.Infrastructure.Services;

public class PdfService : IPdfService
{
    public Task<byte[]> GenerateInvoicePdfAsync(Invoice invoice)
    {
        var html = BuildInvoiceHtml(invoice);

        using var ms = new MemoryStream();
        using var writer = new PdfWriter(ms);
        using var pdf = new PdfDocument(writer);
        HtmlConverter.ConvertToPdf(html, pdf, new ConverterProperties());

        return Task.FromResult(ms.ToArray());
    }

    private static string BuildInvoiceHtml(Invoice invoice)
    {
        var lineItemsHtml = string.Join("", invoice.LineItems.Select(li =>
            $@"<tr>
                <td>{System.Net.WebUtility.HtmlEncode(li.Description)}</td>
                <td style='text-align:center'>{li.Quantity}</td>
                <td style='text-align:right'>${li.UnitPrice:F2}</td>
                <td style='text-align:right'>${li.Amount:F2}</td>
               </tr>"));

        return $@"<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<style>
  body {{ font-family: Arial, sans-serif; font-size: 13px; color: #212529; margin: 40px; }}
  .header {{ display: flex; justify-content: space-between; margin-bottom: 40px; }}
  .invoice-title {{ font-size: 32px; font-weight: bold; color: #1d3557; }}
  .badge {{ padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold;
    background: #2d6a4f; color: white; }}
  table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
  th {{ background: #1d3557; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #dee2e6; }}
  tr:nth-child(even) td {{ background: #f8f9fa; }}
  .totals {{ margin-left: auto; width: 300px; }}
  .totals td {{ padding: 6px 10px; }}
  .total-row td {{ font-weight: bold; font-size: 16px; border-top: 2px solid #1d3557; }}
  .section {{ margin-bottom: 24px; }}
  .label {{ color: #6c757d; font-size: 12px; text-transform: uppercase; }}
</style>
</head>
<body>
<div class='header'>
  <div>
    <div class='invoice-title'>INVOICE</div>
    <div style='font-size:20px; color:#6c757d'>{invoice.InvoiceNumber}</div>
  </div>
  <div style='text-align:right'>
    <div><span class='badge'>{invoice.Status}</span></div>
    <div style='margin-top:8px'>Issue Date: <strong>{invoice.IssueDate:MMM dd, yyyy}</strong></div>
    <div>Due Date: <strong>{invoice.DueDate:MMM dd, yyyy}</strong></div>
  </div>
</div>

<div style='display:flex; gap:60px; margin-bottom:32px'>
  <div class='section'>
    <div class='label'>From</div>
    <div><strong>{System.Net.WebUtility.HtmlEncode(invoice.Tenant?.Name ?? "Company")}</strong></div>
  </div>
  <div class='section'>
    <div class='label'>Bill To</div>
    <div><strong>{System.Net.WebUtility.HtmlEncode(invoice.Client?.Name ?? "")}</strong></div>
    <div>{System.Net.WebUtility.HtmlEncode(invoice.Client?.Email ?? "")}</div>
    <div>{System.Net.WebUtility.HtmlEncode(invoice.Client?.Address ?? "")}</div>
    <div>{System.Net.WebUtility.HtmlEncode(invoice.Client?.City ?? "")} {System.Net.WebUtility.HtmlEncode(invoice.Client?.Country ?? "")}</div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th style='text-align:center'>Qty</th>
      <th style='text-align:right'>Unit Price</th>
      <th style='text-align:right'>Amount</th>
    </tr>
  </thead>
  <tbody>{lineItemsHtml}</tbody>
</table>

<table class='totals'>
  <tr><td>Subtotal</td><td style='text-align:right'>${invoice.SubTotal:F2}</td></tr>
  <tr><td>Tax ({invoice.TaxRate}%)</td><td style='text-align:right'>${invoice.TaxAmount:F2}</td></tr>
  <tr><td>Discount</td><td style='text-align:right'>-${invoice.DiscountAmount:F2}</td></tr>
  <tr class='total-row'><td>Total</td><td style='text-align:right'>${invoice.TotalAmount:F2}</td></tr>
</table>

{(string.IsNullOrEmpty(invoice.Notes) ? "" : $"<div class='section'><div class='label'>Notes</div><div>{System.Net.WebUtility.HtmlEncode(invoice.Notes)}</div></div>")}

<div style='margin-top:60px; color:#6c757d; font-size:11px; border-top:1px solid #dee2e6; padding-top:10px'>
  Generated by InvoicePro &bull; {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC
</div>
</body>
</html>";
    }
}
