export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  INVOICES: '/invoices',
  INVOICE_NEW: '/invoices/new',
  INVOICE_DETAIL: (id = ':id') => `/invoices/${id}`,
  INVOICE_EDIT: (id = ':id') => `/invoices/${id}/edit`,
  INVOICE_PAY: (id = ':id') => `/pay/${id}`,
  CLIENTS: '/clients',
  CLIENT_NEW: '/clients/new',
  CLIENT_EDIT: (id = ':id') => `/clients/${id}/edit`,
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_TENANTS: '/admin/tenants',
  ADMIN_USERS: '/admin/users',
  ADMIN_ANALYTICS: '/admin/analytics',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
}
